link:
  home: "https://www.railstutorial.org/"
  help1: "https://www.railstutorial.org/help"
  help2: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  about1: "https://www.railstutorial.org/"
  about2: "https://www.learnenough.com/"
  about3: "https://www.railstutorial.org/book"
  about4: "https://screencasts.railstutorial.org/"
  about5: "https://rubyonrails.org/"
  footer1: "https://www.railstutorial.org/"
  footer2: "https://www.michaelhartl.com/"
  link_news: "https://news.railstutorial.org/"
  img_size: "200px"

validations:
  user:
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    name_max_length: 50
    email_max_length: 255
    pass_min_length: 6
    checkbox_checked: "1"
    user_per_page: 20
    size_ava: 50
    token_expired: 2
    following_per_page: 10
    followed_per_page: 10
  micropost:
    posts_per_page: 10
    maxium_image_size: 5
    max_length_content: 140
    valid_content_type: ["image/jpeg", "image/gif", "image/png"]
  image:
    img_size: 500
gravatar:
  link: "https://gravatar.com/emails"
