link:
  home: "https://www.railstutorial.org/"
  help1: "https://www.railstutorial.org/help"
  help2: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  about1: "https://www.railstutorial.org/"
  about2: "https://www.learnenough.com/"
  about3: "https://www.railstutorial.org/book"
  about4: "https://screencasts.railstutorial.org/"
  about5: "https://rubyonrails.org/"
  footer1: "https://www.railstutorial.org/"
  footer2: "https://www.michaelhartl.com/"
  link_news: "https://news.railstutorial.org/"
  img_size: "200px"

validations:
  user:
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    name_max_length: 50
    email_max_length: 255
    pass_min_length: 6
    checkbox_checked: "1"
    user_per_page: 20
    size_ava: 50
gravatar:
  link: "https://gravatar.com/emails"
