link:
  home: "https://www.railstutorial.org/"
  help1: "https://www.railstutorial.org/help"
  help2: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  about1: "https://www.railstutorial.org/"
  about2: "https://www.learnenough.com/"
  about3: "https://www.railstutorial.org/book"
  about4: "https://screencasts.railstutorial.org/"
  about5: "https://rubyonrails.org/"
